name: RhubarbRye
favicon: null
layout_spectrum: 0.6585919049102813
typography_spectrum: 0.3146604527719319
title: A Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.34753533476032317
  lightness: 0.1278357277624309
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
