name: RhubarbRye
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51092
title: A Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221618'
    - '#545673'
    - '#c6a6ad'
    - '#6b83aa'
    - '#b97a70'
  brandStrength: 0.5
  lightness: 0.1278357277624309
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
